routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::middleware('guest')->namespace('Auth')->prefix('auth')->name('auth.')->group(function () {
    Route::name('page.')->group(function () {
        Route::get('login', 'LoginController@index')->name('login');
        Route::get('register', 'RegisterController@index')->name('register');
    });

    Route::name('request.')->group(function () {
        Route::post('login', 'LoginController@login')->name('login');
        Route::post('register', 'RegisterController@register')->name('register');
    });
});
Route::get('logout', function () {
    Auth::logout();
    return redirect(route('auth.page.login'));
})->name('logout');

//Panel
Route::middleware('auth')->name('panel.')->prefix('panel')->group(function () {

    Route::resource('company', 'Resources\CompanyController');

    Route::middleware('company.created')->group(function () {

        Route::prefix('api')->name('API')->group(function (){
            Route::resources([
                'clients' => 'ClientController'
            ]);
        });

        Route::resources([
            'clients' => 'Resources\ClientController',
            'leads' => 'Resources\LeadsController',
        ]);

        Route::get('dashboard', 'PanelController@dashboard')->name('dashboard');

        Route::prefix('profile')->name('profile.')->group(function (){
            Route::get('settings', 'PanelController@profile_settings')->name('settings');
        });

        Route::get('dashboard', 'PanelController@dashboard')->name('dashboard');

    });
});
//End panel

//ClientZone

Route::prefix('clientzone')->name('clientzone')->namespace('ClientZone')->group(function (){

});


Route::view('/', 'website.landing')->name('landing');
Route::view('/pricing', 'website.pricing')->name('pricing');

app/Models/Client.php
<?php /** @noinspection PhpUndefinedFieldInspection */

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;
use Laravel\Scout\Searchable;

class Client extends Model
{

    protected $primaryKey = 'uuid';
    public $incrementing = false;

    protected $hidden = ['id'];

    protected $guarded = [];

    protected static function boot()
    {
        parent::boot();

        static::creating(function ($query) {
            $query->uuid = $query->uuid ?? Str::orderedUuid();
        });
    }

    public function company()
    {
        return $this->belongsTo('App\Models\Company', 'company_owner_id');
    }
    public function name( $divider = " " ) {
        if($this->company_as_primary === true) return $this->companyname;
            return $this->firstname . $divider . $this->lastname;

    }

    public function leads(){
        return $this->hasMany('App\Models\Leads', 'client_uuid', 'uuid');
    }
}

app/Http/Controllers/API/ClientController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use App\Models\Client;
use Illuminate\Http\Response;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return JsonResponse|Response
     */
    public function show($id)
    {
        return response()->json( Client::findOrFail($id) );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/PanelController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Faker\Factory;

class PanelController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function dashboard()
    {
        return view('panel.dashboard');
    }
    public function profile_settings()
    {
        return view('panel.profile.settings');
    }


}

app/Http/Controllers/Resources/ClientController.php
<?php

namespace App\Http\Controllers\Resources;

use App\Http\Controllers\Controller;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\Request;
use App\Models\Client;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Validator;
use Auth;
use Illuminate\Validation\ValidationException;
use Illuminate\View\View;
use Faker\Factory as Faker;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|Response|View
     */
    public function index()
    {
        return view('panel.clients.index')->with([
            'clients' => Client::paginate(10)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|Response|View
     */
    public function create()
    {
        return view('panel.clients.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Response
     * @throws ValidationException
     */
    public function store(Request $request)
    {
        $this->validator($request->all())->validate();

        $this->insert($request->all());

        return \response(redirect()->route('panel.clients.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Application|Factory|Response|View
     */
    public function show($id)
    {
        if($client = Client::find($id))
            return view('panel.clients.show')->with([
                'client'    => $client,
                'id'        => $id,
                'faker'     => Faker::create()
            ]);

        return \response(abort(404));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        return \response($id);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        return \response($request, $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        return \response($id);
    }

    protected function validator(array $data)
    {
        return Validator::make($data, [
            'firstname' => ['required', 'string', 'max:255'],
            'lastname' => ['nullable', 'string', 'max:255'],
            'companyname' => ['nullable','string', 'max:255'],
            'email' => ['required', 'email', 'max:255'],
            'phone' => ['nullable', 'string', 'max:15'],
            'aditional' => ['nullable', 'string','max:1024'],

        ]);
    }

    /**
     * Create a new user instance after a valid registration.
     *
     * @param  array  $data
     * @return Client
     */
    protected function insert(array $data)
    {

        return Client::create([
            'company_owner_id' => Auth::user()->company->id,
            'firstname' => $data['firstname'],
            'lastname' => $data['lastname'],
            'companyname' => $data['companyname'],
            'email' => $data['email'],
            'phone' => $data['phone'],
            'aditional' => $data['aditional'],
            'company_as_primary' => (isset($data['company_as_primary']) && $data['company_as_primary'] === "on")

        ]);
    }
}

app/View/Components/Clients/Requests.php
<?php

namespace App\View\Components\Clients;

use Illuminate\View\Component;

class Requests extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\View\View|string
     */
    public function render()
    {
        return view('components.clients.requests');
    }
}

resources/views/panel/clients/create.blade.php
@extends('layouts.panel-page')

@push('links')
    <link rel="stylesheet" type="text/css" href="{{ URL::asset('assets/libs/bootstrap-datepicker/bootstrap-datepicker.min.css')}}">
        <!-- dropzone css -->
    <link rel="stylesheet" type="text/css" href="{{ URL::asset('assets/libs/dropzone/dropzone.min.css')}}">
@endpush

@push('page.content')
    <div class="container-fluid">

        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box d-flex align-items-center justify-content-between">
                    <h4 class="mb-0 font-size-18">Create New Client</h4>

                    <div class="page-title-right">
                        <ol class="breadcrumb m-0">
                            <li class="breadcrumb-item"><a href="javascript: void(0);">Clients</a></li>
                            <li class="breadcrumb-item active">Create New </li>
                        </ol>
                    </div>

                </div>
            </div>
        </div>
        <!-- end page title -->

        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title mb-4">Client info</h4>
                        <form method="POST" action="{{ route('panel.clients.store') }}">
                            @csrf

                            <div class="row">
                                <div class="col-md-6">
                                    <x-apps.input name="firstname" type="text">
                                        First Name
                                    </x-apps.input>

                                </div>
                                <div class="col-md-6">
                                    <x-apps.input name="lastname" type="text">
                                        Last Name
                                    </x-apps.input>
                                </div>
                                <div class="col-md-12">

                                    <x-apps.input name="companyname" type="text">
                                        Company name
                                    </x-apps.input>
                                    <div class="custom-control custom-checkbox custom-checkbox-outline custom-checkbox-primary mb-3">
                                        <input name="company_as_primary" type="checkbox" class="custom-control-input" id="company_as_primary">
                                        <label class="custom-control-label" for="company_as_primary">Company name as primary name</label>
                                    </div>
                                </div>


                            </div>

                            <div class="row">
                                <div class="col-lg-12">
                                    <x-apps.input name="email" type="email">
                                        Email
                                    </x-apps.input>

                                </div>
                            </div>

                            <div class="row">
                                <div class="col-lg-12">

                                    <x-apps.input name="phone" type="text">
                                        Phone
                                    </x-apps.input>
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="formrow-aditional-input">Aditional info</label>
                                        <textarea rows="6" name="aditional" type="text" class="form-control @error('aditional') is-invalid @enderror" id="formrow-aditional-input">{{old('aditional')}}</textarea>
                                        @error('aditional')
                                            <div class="invalid-feedback">
                                                {{ $message }}
                                            </div>
                                        @enderror
                                    </div>
                                </div>
                            </div>


                            <div>
                                <button type="submit" class="btn btn-primary w-md">Submit</button>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
        <!-- end row -->

    </div> <!-- container-fluid -->
@endpush

@push('scripts')
@endpush

resources/views/panel/clients/index.blade.php
@extends('layouts.panel-page')

@push('page.content')
    <div class="container-fluid">

        <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box d-flex align-items-center justify-content-between">
                <h4 class="mb-0 font-size-18">User List</h4>

                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item active">Contacts</li>
                        <li class="breadcrumb-item">User List</li>
                    </ol>
                </div>

            </div>
        </div>
    </div>
     <!-- end page title -->

    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div class="row mb-2">
                        <div class="col-sm-4">
                            <div class="search-box mr-2 mb-2 d-inline-block">
                                <div class="position-relative">
                                    <input type="text" class="form-control" placeholder="Search...">
                                    <i class="bx bx-search-alt search-icon"></i>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-8">
                            <div class="text-sm-right">
                                <a href="{{ route('panel.clients.create') }}">
                                    <button type="button" class="btn btn-success btn-rounded waves-effect waves-light mb-2 mr-2">
                                        <i class="mdi mdi-plus mr-1"></i> Create new client
                                    </button>
                                </a>
                            </div>
                        </div><!-- end col-->
                    </div>
                    <div class="table-responsive">
                        <table class="table table-centered table-nowrap table-hover">
                            <thead class="thead-light">
                                <tr>
                                    <th scope="col" style="width: 70px;">#</th>
                                    <th scope="col">Name</th>
                                    <th scope="col">Email</th>
                                    <th scope="col">Tags</th>
                                    <th scope="col">Projects</th>
                                    <th scope="col">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($clients as $client)

                                    <tr data-href="{{route('panel.clients.show', $client->uuid)}}">
                                        <td>
                                            <div class="avatar-xs">
                                                <span class="avatar-title rounded-circle">
                                                    {{$client->firstname[0]}}
                                                </span>
                                            </div>
                                        </td>
                                        <td>
                                            <h5 class="font-size-14 mb-1"><a href="{{ route('panel.clients.show', $client->uuid)}}" class="text-dark">{{$client->name()}}</a></h5>
                                            @if($client->companyname)
                                                <p class="text-muted mb-0">{{$client->companyname}}</p>
                                            @endif
                                        </td>
                                        <td>{{$client->email}}</td>
                                        <td>
                                            <div>
                                                <a href="#" class="badge badge-soft-primary font-size-11 m-1"></a>
                                                <a href="#" class="badge badge-soft-primary font-size-11 m-1"></a>
                                            </div>
                                        </td>
                                        <td>
                                            125
                                        </td>
                                        <td>
                                            <ul class="list-inline font-size-20 contact-links mb-0">
                                                <li class="list-inline-item px-2">
                                                    <a href="" data-toggle="tooltip" data-placement="top" title="" data-original-title="Message"><i class="bx bx-message-square-dots"></i></a>
                                                </li>
                                                <li class="list-inline-item px-2">
                                                    <a href="" data-toggle="tooltip" data-placement="top" title="" data-original-title="Profile"><i class="bx bx-user-circle"></i></a>
                                                </li>
                                            </ul>
                                        </td>
                                    </tr>

                                @endforeach

                            </tbody>
                        </table>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            {{ $clients->links('components.apps.pagination') }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endpush