routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::middleware('guest')->namespace('Auth')->prefix('auth')->name('auth.')->group(function () {
    Route::name('page.')->group(function () {
        Route::get('login', 'LoginController@index')->name('login');
        Route::get('register', 'RegisterController@index')->name('register');
    });

    Route::name('request.')->group(function () {
        Route::post('login', 'LoginController@login')->name('login');
        Route::post('register', 'RegisterController@register')->name('register');
    });
});
Route::get('logout', function () {
    Auth::logout();
    return redirect(route('auth.page.login'));
})->name('logout');

//Panel
Route::middleware('auth')->name('panel.')->prefix('panel')->group(function () {

    Route::resource('company', 'Resources\CompanyController');

    Route::middleware('company.created')->group(function () {

        Route::prefix('api')->name('API')->group(function (){
            Route::resources([
                'clients' => 'ClientController'
            ]);
        });

        Route::resources([
            'clients' => 'Resources\ClientController',
            'leads' => 'Resources\LeadsController',
        ]);

        Route::get('dashboard', 'PanelController@dashboard')->name('dashboard');

        Route::prefix('profile')->name('profile.')->group(function (){
            Route::get('settings', 'PanelController@profile_settings')->name('settings');
        });

        Route::get('dashboard', 'PanelController@dashboard')->name('dashboard');

    });
});
//End panel

//ClientZone

Route::prefix('clientzone')->name('clientzone')->namespace('ClientZone')->group(function (){

});


Route::view('/', 'website.landing')->name('landing');
Route::view('/pricing', 'website.pricing')->name('pricing');

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Company extends Model
{

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'owner_id', 'industry_slug', 'size', 'phone', 'websiteurl'
    ];

    public $timestamps = true;


    protected static function boot()
    {
        parent::boot();

        static::creating(function ($query) {
            $query->slug = $query->slug ?? Str::slug($query->name, '-');
        });
    }

    public function owner()
    {
        return $this->belongsTo('App\User', 'owner_id');
    }
    public function clients()
    {
        return $this->hasMany('App\Models\Client', 'company_owner_id');
    }
}

app/Http/Controllers/PanelController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Faker\Factory;

class PanelController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function dashboard()
    {
        return view('panel.dashboard');
    }
    public function profile_settings()
    {
        return view('panel.profile.settings');
    }


}

app/Http/Controllers/Resources/CompanyController.php
<?php

namespace App\Http\Controllers\Resources;

use App\Http\Controllers\Controller;
use App\User;
use App\Models\{Company, IndustryCategory};
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Auth;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Validator;
use Illuminate\View\View;
use function redirect;
use function response;

class CompanyController extends Controller
{
    public function __construct()
    {
        $this->middleware('company.created', ['except' => ['create', 'store']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        return Company::all();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|Response|View
     */
    public function create()
    {
        if(Auth::user()->company){
            return response(404);
        }

        return view('panel.company.create')->with([
            'industry_categories' => IndustryCategory::get()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return RedirectResponse|Response
     */
    public function store(Request $request)
    {

        $this->validator($request->all())->validate();

        $this->insert($request->all());

        return redirect()->route('panel.dashboard');

    }

    /**
     * Display the specified resource.
     *
     * @param Company $company
     * @return Response
     */
    public function show(Company $company)
    {
        return $company;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Company $company
     * @return Response
     */
    public function edit(Company $company)
    {
        return $company;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Company $company
     * @return Response
     */
    public function update(Request $request, Company $company)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Company $company
     * @return Response
     */
    public function destroy(Company $company)
    {
        //
    }

    /**
    * Get a validator for an incoming creation request.
     *
     * @param  array  $data
     * @return \Illuminate\Contracts\Validation\Validator
     */
    protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => ['required', 'string', 'max:255'],
            'size' => ['required', 'numeric', 'max:4', 'min:1'],
            'phone' => ['required', 'string', 'max:15'],
            'industry_slug' => ['required', 'string', 'exists:industries,slug'],
            'websiteurl'    => ['max:255']
        ]);
    }

    /**
     * Create a new user instance after a valid registration.
     *
     * @param  array  $data
     * @return User
     */
    protected function insert(array $data)
    {
        return Company::create([
            'owner_id' => Auth::id(),
            'industry_slug' => $data['industry_slug'],
            'name' => $data['name'],
            'size' => $data['size'],
            'phone' => $data['phone'],
            'websiteurl' => $data['websiteurl']
        ]);
    }
}

resources/views/panel/company/create.blade.php
@extends('layouts.auth-page')
@push('content')

    <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="card overflow-hidden">
            <div class="bg-soft-primary">
                <div class="row">
                    <div class="col-7">
                        <div class="text-primary p-4">
                            <h5 class="text-primary">Set up your company</h5>
                            <p>Give us some additional data about your company.</p>
                        </div>
                    </div>
                    <div class="col-5 align-self-end">
                        <img src="{{ asset('assets/images/company/business.svg') }}" alt="" class="img-fluid">
                    </div>


                </div>
            </div>
            <div class="card-body pt-0">
                <div class="row">
                    <div class="col-4">
                        <a href="index.html">
                            <div class="avatar-md profile-user-wid mb-4">
                                <span class="avatar-title rounded-circle bg-light">
                                    <img src="{{ asset('assets/images/logo.png') }}" alt="" class="rounded-circle" height="55">
                                </span>
                            </div>
                        </a>
                    </div>

                    <div class="col-8 text-right">

                            <button type="button" class="btn header-item text-right" id="page-header-user-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="d-inline-block ml-1">{{ Auth::user()->email }}</span>
                                <div class="avatar-xs d-inline-block ml-1">
                                    <span class="avatar-title rounded-circle">
                                        {{ Auth::user()->firstname[0] }}
                                    </span>
                                </div>
                                <i class="mdi mdi-chevron-down d-inline-block"></i>
                            </button>
                            <div class="dropdown-menu dropdown-menu-right" style="">

                                <a class="dropdown-item text-danger" href="{{ route('logout') }}"><i class="bx bx-power-off font-size-16 align-middle mr-1 text-danger"></i> Logout</a>
                            </div>

                    </div>
                </div>


                <x-auth.steps :step="2"/>

                <div class="p-2">
                <form class="form-horizontal" method="POST" action="{{ route('panel.company.store') }}">

                    @csrf
                    <div class="row">
                        <div class="col-12">
                            <div class="form-group">
                                <label for="companyname">Company name</label>
                                <input value="{{ old('name') }}" name="name" type="text" autocomplete="companyname"
                                class="form-control @error('name') is-invalid @enderror" id="companyname" placeholder="Enter company name">
                                @error('name')
                                    <div class="invalid-feedback">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>

                        </div>

                        <div class="col-6">
                            <div class="form-group">
                                <label for="companysize">Company size</label>
                                <div class="col-lg-12 pl-0 pr-0">
                                    <select name="size" class="custom-select  @error('size') is-invalid @enderror" id="companysize">
                                        <option value="" selected="">Workers count</option>
                                        <option value="1">Just me</option>
                                        <option value="2">2-3 people</option>
                                        <option value="3">4-10 people</option>
                                        <option value="4">10+ people</option>
                                    </select>
                                    @error('size')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                            </div>
                        </div>

                        <div class="col-6">
                            <div class="form-group">
                                <label for="companyphone">Phone number</label>
                                <input value="{{ old('phone') }}" name="phone" type="tel" autocomplete="companyphone"
                                class="form-control @error('phone') is-invalid @enderror" id="companyphone" placeholder="Enter phone number">
                                @error('phone')
                                    <div class="invalid-feedback">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
                        </div>

                        <div class="col-12">
                            <div class="form-group">
                                <label class="control-label" for="companyindustry">Industry</label>
                                <select name="industry_slug" class="form-control @error('industry_slug') is-invalid @enderror custom-select" id="companyindustry">
                                    <option value="">Select</option>
                                    @foreach ($industry_categories as $industry_category)
                                        <optgroup label="{{ $industry_category->name }}">
                                            @foreach ($industry_category->industries as $industry)
                                                <option value="{{$industry->slug}}">{{$industry->name}}</option>
                                            @endforeach


                                        </optgroup>
                                    @endforeach
                                </select>
                                @error('industry_slug')
                                    <div class="invalid-feedback">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
                        </div>
                        <div class="col-12">

                            <div class="custom-control custom-checkbox custom-checkbox-outline custom-checkbox-primary mb-3">
                                <input type="checkbox" class="custom-control-input" id="customCheck-outlinecolor1">
                                <label class="custom-control-label" for="customCheck-outlinecolor1">We already have a website</label>
                            </div>
                            <div class="collapse form-group" id="collapseExample" style="">

                                <input value="{{ old('websiteurl') }}" name="websiteurl" type="text" autocomplete="websiteurl"
                                class="form-control @error('websiteurl') is-invalid @enderror" id="websiteurl" placeholder="Url of your website">
                                @error('websiteurl')
                                    <div class="invalid-feedback">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
                        </div>
                    </div>



                    <div class="mt-4">
                      <button class="btn btn-primary btn-block waves-effect waves-light" type="submit">Continue</button>
                    </div>
                </form>
                </div>


            </div>
        </div>


    </div>

@endpush