routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::middleware('guest')->namespace('Auth')->prefix('auth')->name('auth.')->group(function () {
    Route::name('page.')->group(function () {
        Route::get('login', 'LoginController@index')->name('login');
        Route::get('register', 'RegisterController@index')->name('register');
    });

    Route::name('request.')->group(function () {
        Route::post('login', 'LoginController@login')->name('login');
        Route::post('register', 'RegisterController@register')->name('register');
    });
});
Route::get('logout', function () {
    Auth::logout();
    return redirect(route('auth.page.login'));
})->name('logout');

//Panel
Route::middleware('auth')->name('panel.')->prefix('panel')->group(function () {

    Route::resource('company', 'Resources\CompanyController');

    Route::middleware('company.created')->group(function () {

        Route::prefix('api')->name('API')->group(function (){
            Route::resources([
                'clients' => 'ClientController'
            ]);
        });

        Route::resources([
            'clients' => 'Resources\ClientController',
            'leads' => 'Resources\LeadsController',
        ]);

        Route::get('dashboard', 'PanelController@dashboard')->name('dashboard');

        Route::prefix('profile')->name('profile.')->group(function (){
            Route::get('settings', 'PanelController@profile_settings')->name('settings');
        });

        Route::get('dashboard', 'PanelController@dashboard')->name('dashboard');

    });
});
//End panel

//ClientZone

Route::prefix('clientzone')->name('clientzone')->namespace('ClientZone')->group(function (){

});


Route::view('/', 'website.landing')->name('landing');
Route::view('/pricing', 'website.pricing')->name('pricing');

app/Models/Leads.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Leads extends Model
{
    protected $primaryKey = 'uuid';
    public $incrementing = false;

    protected $guarded = [];

    protected static function boot()
    {
        parent::boot();

        static::creating(function ($query) {
            $query->uuid = $query->uuid ?? Str::orderedUuid();
        });
    }


    public function client()
    {
        return $this->belongsTo('App\Models\Client', 'client_uuid', 'uuid');
    }

    public function company()
    {
        return $this->belongsTo('App\Models\Company', 'company_id');
    }

}

app/Http/Controllers/PanelController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Faker\Factory;

class PanelController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function dashboard()
    {
        return view('panel.dashboard');
    }
    public function profile_settings()
    {
        return view('panel.profile.settings');
    }


}

app/Http/Controllers/Resources/LeadsController.php
<?php

namespace App\Http\Controllers\Resources;

use App\Http\Controllers\Controller;
use App\Models\Leads;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Validator;

use Auth;
use Illuminate\Validation\ValidationException;
use Illuminate\View\View;
use function response;

class LeadsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|Response|View
     */
    public function index()
    {
        return view('panel.leads.index')->with([
            'leads' => Leads::paginate(15)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|Response|View
     */
    public function create()
    {
        return view('panel.leads.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return RedirectResponse|Response
     * @throws ValidationException
     */
    public function store(Request $request)
    {
        $this->validator($request->all())->validate();

        $this->insert($request->all());

        return redirect()->route('panel.leads.index');
    }

    /**
     * Display the specified resource.
     *
     * @param $uuid
     * @return Application|Factory|Response|View
     */
    public function show($uuid)
    {
        return view('panel.leads.show')->with([
            'lead'  => Leads::find($uuid)
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Leads $leads
     * @return Response
     */
    public function edit(Leads $leads)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Leads $leads
     * @return Response
     */
    public function update(Request $request, Leads $leads)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Leads $leads
     * @return Response
     */
    public function destroy(Leads $leads)
    {
        //
    }

    protected function validator(array $data)
    {
        return Validator::make($data, [
            'aditional' => ['nullable', 'string', 'max:1024'],
            'title' => ['required', 'string', 'max:255'],
            'client_uuid' => ['required', 'uuid']
        ]);
    }

    /**
     * Create a new user instance after a valid registration.
     *
     * @param  array  $data
     * @return Leads
     */
    protected function insert(array $data)
    {
        return Leads::create([
            'company_id' => Auth::user()->company->id,
            'client_uuid'=> $data['client_uuid'],
            'aditional' => $data['aditional'],
            'title' => $data['title']
        ]);
    }
}

resources/views/panel/leads/create.blade.php
@extends('layouts.panel-page')

@push('links')
    <link href="{{ asset('assets/libs/bootstrap-editable/bootstrap-editable.min.css') }}" rel="stylesheet" type="text/css">
@endpush

@push('page.content')
    <div class="container-fluid">

        <x-page-title>
            Create new request
        </x-page-title>

        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <form method="POST" action="{{ route('panel.leads.store') }}">
                            @csrf
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group title mb-4">
                                        <h3>
                                            Request for <span type="button" data-toggle="modal" data-target=".choose-user" class="pointer editable editable-pre-wrapped editable-click editable-unsaved user-name">not selected</span>
                                            <input type="hidden" name="client_uuid">
                                        </h3>

                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <x-apps.input name="title" type="text">
                                        Title
                                    </x-apps.input>

                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="formrow-aditional-input">Aditional info</label>
                                        <textarea rows="6" name="aditional" type="text" class="form-control @error('aditional') is-invalid @enderror" id="formrow-aditional-input">{{old('aditional')}}</textarea>
                                        @error('aditional')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                        @enderror
                                    </div>
                                </div>
                            </div>





                            <div>
                                <button type="submit" class="btn btn-primary w-md">Submit</button>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
        <!-- end row -->

    </div> <!-- container-fluid -->


    <x-modals.select-user/>

    <x-modals.create-user/>
@endpush

@push('scripts')
@endpush

resources/views/panel/leads/index.blade.php
@extends('layouts.panel-page')

@push('page.content')
    <div class="container-fluid">

        <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box d-flex align-items-center justify-content-between">
                <h4 class="mb-0 font-size-18">Requests List</h4>

                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item active">Contacts</li>
                        <li class="breadcrumb-item">User List</li>
                    </ol>
                </div>

            </div>
        </div>
    </div>
     <!-- end page title -->

    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div class="row mb-2">
                        <div class="col-sm-4">
                            <div class="search-box mr-2 mb-2 d-inline-block">
                                <div class="position-relative">
                                    <input type="text" class="form-control" placeholder="Search...">
                                    <i class="bx bx-search-alt search-icon"></i>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-8">
                            <div class="text-sm-right">
                                <a href="{{ route('panel.leads.create') }}">
                                    <button type="button" class="btn btn-success btn-rounded waves-effect waves-light mb-2 mr-2">
                                        <i class="mdi mdi-plus mr-1"></i> Create new request
                                    </button>
                                </a>
                            </div>
                        </div><!-- end col-->
                    </div>
                    <div class="table-responsive">
                        <table class="table table-centered table-nowrap table-hover">
                            <thead class="thead-light">
                                <tr>
                                    <th scope="col">Client</th>
                                    <th scope="col">Title</th>
                                    <th scope="col">Contact</th>
                                    <th scope="col">Created</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($leads as $lead)

                                        <tr data-href="{{ route('panel.leads.show', $lead->uuid) }}">

                                            <td>
                                                <a href="{{ route('panel.clients.show', $lead->client->uuid) }}">
                                                    <div class="d-flex justify-content-start align-items-center">


                                                        <div class="avatar-xs">
                                                            <span class="avatar-title rounded-circle">
                                                                {{$lead->client->firstname[0]}}
                                                            </span>
                                                        </div>
                                                        <div class="d-flex ml-2">
                                                            <span>
                                                                {{ $lead->client->name() }}
                                                            </span>
                                                        </div>
                                                    </div>
                                                </a>

                                            </td>

                                            <td>
                                                {{ $lead->title }}
                                            </td>
                                            <td>{{$lead->client->email}}</td>

                                            <td>
                                                {{ $lead->created_at }}
                                            </td>

                                        </tr>

                                @endforeach

                            </tbody>
                        </table>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            {{ $leads->links('components.apps.pagination') }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endpush

resources/views/panel/leads/show.blade.php
@extends('layouts.panel-page')

@push('links')

@endpush

@push('page.content')

    @dd( $lead )

@endpush

@push('scripts')

@endpush